server:
  port: 8001
  servlet:
    context-path: "/member"

spring:
  application:
    name: "member"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train-member?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: train_member
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml