POST  http://localhost:8000/member/member/login
Content-Type:application/json

{
  "mobile": "19816896292",
  "code": "8888"
}

> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.data.token));
    client.global.set("token", response.body.data.token);
%}

###
GET http://localhost:8000/member/member/count
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/member/register
Content-Type:application/json

{
  "mobile": "19816896291"
}

###

POST http://localhost:8000/member/member/send-code
Content-Type:application/json

{
  "mobile": "19816896292"
}

###

POST http://localhost:8000/member/passenger/save
Content-Type:application/json
token: {{token}}

{
  "name": "test",
  "idCard": "1234567",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=10
Accept: application/json
token: {{token}}

###
DELETE http://localhost:8000/member/passenger/delete/1678361873763930112
Accept: application/json
token: {{token}}

### 演示更新
POST http://localhost:8000/member/passenger/save
Content-Type:application/json
token: {{token}}

{
  "id": 1678373993377304576,
  "name": "test2",
  "idCard": "1234567890",
  "type": "2"
}