server:
  port: 8000

# 路由转发，将/member/...的请求转发了member模块
spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      routes:
        - id: member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
